site_name: "Iridescence"
site_author: k.koide
repo_url: https://github.com/koide3/iridescence
site_url: https://koide3.github.io/iridescence/
site_description: "Iridescence: Visualization library for rapid prototyping of 3D point cloud algorithms"

theme: 
    name: material
    palette:
        primary: indigo
    front:
        text: Roboto

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: ja
          name: 日本語
          build: true


markdown_extensions:
    - meta
    - attr_list
    - admonition
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

copyright: Copyright &copy; 2021 - 2022 Kenji Koide
extra:
    social:
        - icon: material/home
          link: https://staff.aist.go.jp/k.koide/
        - icon: fontawesome/brands/github
          link: https://github.com/koide3/iridescence
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/k_koide3

extra_css:
    - "css/custom.css"
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"

nav:
    - 'index.md'
    - 'basic.md'
    - 'shader.md'
    - 'drawables.md'
    - 'controls.md'
    - 'picking.md'
    - 'multithread.md'
    - 'effects.md'
    - 'cookbook.md'
    - 'misc.md'